services:
  - type: web
    name: plantor-admin
    env: static
    buildCommand: "cd admin-web && npm install && npm run build"
    staticPublishPath: "./admin-web/dist"
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
